### ISSUE TITLE
Parameter representing files

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#69] opened 2018-07-25 16:53 UTC
Now that we've defined the basic properties of a parameter definition, we should focus on parameters for data files, such as

  * models
  * configuration files
  * masks
  * etc.

I think they should extend this schema:

```json
{
  "type": "string",
  "format": "uri",
  "dereference": "true",
  "content-type": "application/vnd.ocropy.pyrnn",
  "cacheable": true,
}
```

`type` and `format` are clear I think.

`dereference` would signify that to get the value of the parameter the uri needs to be resolved and the resolved value used as the parameter value.

`content-type` specifies the type of data that is to be expected and should be sent as the `Accept` header of the dereferencing agent.

`cacheable` is a boolean to define whether the dereferencing agent should use HTTP caching mechanics when retrieving the document (`ETag` and such) to avoid having to download files again and again.

**Comment by VolkerHartmann** [comment] 2018-09-18 07:40
I'm afraid I don't understand the background.
Parameters are already completely defined by the following attributes:
type, format, description, required, default, enum.
Why should we add these additional attributes?
We are not able to check the correctness of the parameters in every
case.
I think that the modules are responsible for dereferencing the URI. 
They also should know the content-type of the referenced file.
Maybe model, configuration files, masks, ... are not public readable.  
If so we had to add some token or username/password or ... to access the file.
In case of parallelization caching mechanisms may be useless. 
If we want to improve runtime performance external URIs may stored locally if possible.

**Comment by kba** [comment] 2018-09-20 15:11
The advantages of differentiating between strings and strings that point to files:

* Documentation: The definition of the parameter contains information on what kind of file is expected and that it is a URL to a file not a string or relative file path etc.
* Cacheability: If a parameter represents a file and it is marked as cacheable, the workflow engine (or OCR-D/core) will be able to download the file once and proxy subsequent requests accordingly.
* Validation: Having additional information can help the workflow engine spot problems (such as differing content-types or suspiciously small sizes or HTTP error codes)

Whether and how workflow engines decide to act upon this information is beyond the spec. But having useful information is better than not having that information.

What are the advantages of making references to files indistinguishable from strings?

**Comment by VolkerHartmann** [comment] 2018-09-21 06:36
That's not the point. Of course, we should distinguish between files and strings.
But we should not try to solve all possible problems in advance, otherwise the solution becomes too complicated and error-prone.
Documentation is similar to Description, right? It's already there and cannot be interpreted by a machine.
Cacheability: Marking a file cacheable is a good idea. This means the content of the file is not changed. It could be downloaded once. I think this should be done on workflow level. 
Validation: The workflow engine does not have to recognize any problems that go beyond the question of whether the file exists/is reachable (Even this may a problem if the file is not public available). If e.g. the format is wrong the modules should throw an exception. This may lead to code duplication, but we cannot possibly support all (future) formats.
Formats may change because an algorithm needs additional information. We can't foresee if the format will change and we shouldn't take over the tasks of the module projects because they have to parse and interpret the files anyway.
In an automated workflow everything should be tested in beforehand. Otherwise you lost.
If validation fails what should the workflow do? Maybe the module can handle this kind of file.
Convenience: The only convenience that the module projects can have is that the files are locally available. Everything else should be left to the module projects.
--> Cacheable is the only additional attribute we need

**Comment by kba** [comment] 2018-09-21 07:49
I still don't see what's wrong about `content-type`.  Whether software agents take action on it or not is beyond the specs, agreed. But I don't understand why that would not be interpretable by a machine? Content-Negotiation is a fundamental feature of many protocols. In fact I would even consider making it an array of possible values. If a server properly implements Conneg and there are multiple manifestations of the same data (say, the pyrnn and pronn representation of the same model), how should ocrd_ocropy express it wants pyrnn and ocrd_kraken that it wants pronn?

Imagine a user interface with a list of files on the left side and a form for task configuration on the right. Having content type information on both the files and file fields would allow you to highlight which files can be dragged to which file fields.

Documenting file formats used is essential for documentation, reproducibility and provenance and worth the effort. I've started that here: https://github.com/kba/docr/blob/master/ocr-backend/media-types.js

**Comment by VolkerHartmann** [comment] 2018-09-21 10:49
You're right, I missed that. 
The content type is also necessary because it may be needed for the download.
> But I don't understand why that would not be interpretable by a machine? 
The documentation attribute is not interpretable! (Isn't it a duplicate of description?)

**Comment by kba** [comment] 2018-09-21 11:18
> The documentation attribute is not interpretable! (Isn't it a duplicate of description?)

There is no attribute `documentation`, just the three I proposed initially. The list [above](https://github.com/OCR-D/spec/issues/69#issuecomment-423220615) were the advantages I see in this proposal not a set of attributes.

OK, so do we agree to add `cacheable` and `content-type` as new fields, basically the initial proposal sans the `dereference` field?

**Comment by VolkerHartmann** [comment] 2018-10-01 05:37
:+1:

**Comment by wrznr** [comment] 2018-10-04 13:12
@VolkerHartmann @kba  Can this agreement be formalised somewhere?

**Comment by kba** [comment] 2018-10-04 13:16
Extending docs on and updating the ocrd tool json schema mostly. The latter requires new release of core and should be tested and documented so I pushed it until next week.

**Closed** 2018-10-19 13:01 UTC
Labels: discussion, interface
